version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./M#_demo.sln && dotnet publish ./M#_demo.sln -c Release -o ./obj/Docker/publish"
